services:
  nginx:
    build: 
      context: ./nginx
    restart: unless-stopped
    volumes:
      - ./html:/var/www/html
      - ./nginx/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
      - 443:443

  db:
    image: mysql:8.3.0
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ./raw_db:/var/lib/mysql
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: XMtepb3Ftbrf

  mailpit:
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - 8025:8025
    environment:
      MP_MAX_MESSAGES: 5000
      MP_DATABASE: /home/mailpit.db